routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function(){
    Route::get('wallets/show/all', 'WalletController@all_wallet')->name('wallets.all');
    Route::get('wallets/show/active', 'WalletController@wallet_active')->name('wallets.active');
    Route::get('wallets/show/not-active', 'WalletController@wallet_not_active')->name('wallets.not-active');
    Route::patch('wallets/update/status/{id}/{status}', 'WalletController@update_status')->name('wallets.update.status');
    Route::resource('wallets', 'WalletController');

    Route::get('categories/show/all', 'CategoryController@all_category')->name('categories.all');
    Route::get('categories/show/active', 'CategoryController@category_active')->name('categories.active');
    Route::get('categories/show/not-active', 'CategoryController@category_not_active')->name('categories.not-active');
    Route::patch('categories/update/status/{id}/{status}', 'CategoryController@update_status')->name('categories.update.status');
    Route::resource('categories', 'CategoryController');

    Route::get('transactions/create/wallet-in', 'TransactionController@create_wallet_in')->name('transactions.create.wallet-in');
    Route::get('transactions/show/wallet-in', 'TransactionController@wallet_in')->name('transactions.wallet-in');
    Route::post('transactions/process/wallet-in', 'TransactionController@process_wallet_in')->name('transactions.process.wallet-in');

    Route::get('transactions/create/wallet-out', 'TransactionController@create_wallet_out')->name('transactions.create.wallet-out');
    Route::get('transactions/show/wallet-out', 'TransactionController@wallet_out')->name('transactions.wallet-out');
    Route::post('transactions/process/wallet-out', 'TransactionController@process_wallet_out')->name('transactions.process.wallet-out');

    Route::get('report/transactions/view', 'ReportController@view_report')->name('reports.view');
    Route::get('report/transactions/show', 'ReportController@show_report')->name('reports.show');
});

app/Wallet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use App\Wallet;
use App\WalletStatus;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class WalletController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $count_all = DB::table('wallets')->count();
        $count_active = DB::table('wallets')->where('status', 1)->count();
        $count_not_active = DB::table('wallets')->where('status', 2)->count();

        $wallets = Wallet::all();

        return view('wallets.index', [
            'wallets' => $wallets,
            'count_not_active' => $count_not_active,
            'count_active' => $count_active,
            'count_all' => $count_all
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $wallet_statuses = WalletStatus::orderBy('name', 'asc')
                            ->get();

        return view('wallets.create', [
            'wallet_statuses' => $wallet_statuses
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:5',
            'description' => 'max:100',
            'wallet_status_id' => 'required',
            'status' => 'required'
         ]);

         Wallet::create([
            'name' => $request->name,
            'reference' => $request->reference,
            'description' => $request->description,
            'wallet_status_id' => $request->wallet_status_id,
            'status' => $request->status
         ]);

         return redirect()->route('wallets.index')->with('success', 'Data dompet berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $wallet = Wallet::find($id);
        return view('wallets.show', ['wallet' => $wallet]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $wallet = Wallet::find($id);
        $wallet_statuses = WalletStatus::orderBy('name', 'asc')
                            ->get();

        return view('wallets.edit', [
            'wallet' => $wallet,
            'wallet_statuses' => $wallet_statuses
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $wallet = Wallet::find($id);
        $wallet->update([
            'name' => $request->name,
            'reference' => $request->reference,
            'description' => $request->description,
            'wallet_status_id' => $request->wallet_status_id
        ]);

        return redirect()->route('wallets.index')->with('success', 'Data dompet berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function update_status(Request $request, $id, $status)
    {
        $wallet_status = Wallet::find($id);
        $wallet_status->update([
            'status' => $status
        ]);

        return redirect()->route('wallets.index')->with('success', 'Status dompet berhasil diubah!');
    }

    public function wallet_active()
    {
        $wallets = DB::table('wallets')
            ->where('status', 1)
            ->get();

        $count_all = DB::table('wallets')
                        ->count();

        $count_active = DB::table('wallets')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('wallets')
            ->where('status', 2)
            ->count();

        return view('wallets.active', [
            'wallets' => $wallets,
            'count_not_active' => $count_not_active,
            'count_active' => $count_active,
            'count_all' => $count_all
        ]);
    }

    public function wallet_not_active()
    {
        $wallets = DB::table('wallets')
            ->where('status', 2)
            ->get();

        $count_all = DB::table('wallets')
                        ->count();

        $count_active = DB::table('wallets')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('wallets')
            ->where('status', 2)
            ->count();

        return view('wallets.active', [
            'wallets' => $wallets,
            'count_active' => $count_active,
            'count_not_active' => $count_not_active,
            'count_all' => $count_all
        ]);
    }

    public function all_wallet()
    {
        $wallets = DB::table('wallets')
                ->get();

        $count_all = DB::table('wallets')
                    ->count();

        $count_active = DB::table('wallets')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('wallets')
            ->where('status', 2)
            ->count();

        return view('wallets.all_wallet', [
            'wallets' => $wallets,
            'count_active' => $count_active,
            'count_not_active' => $count_not_active,
            'count_all' => $count_all
        ]);
    }
}

resources/views/wallets/active.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'Tambah Dompet')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">DOMPET - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('wallets.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('wallets.all') }}" class="btn btn-secondary">Semua ({{ $count_all }})</a>
                    <a href="{{ route('wallets.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('wallets.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-wallet">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>NAMA</th>
                        <th>REFERENSI</th>
                        <th>DESKRIPSI</th>
                        <th>STATUS</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($wallets as $wallet)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $wallet->name }}</td>
                            <td>{{ $wallet->reference }}</td>
                            <td>{{ $wallet->description }}</td>
                            <td>{{ $wallet->status == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <li class="mb-2">{{ $wallet->name }}</li>
                                      <li><a href="{{ route('wallets.show', $wallet->id) }}"><i class="fas fa-search" style="color: #3056c8;"></i> Detail</a></li>
                                      <li><a href="{{ route('wallets.edit', $wallet->id) }}"><i class="fas fa-edit" style="color: #3056c8;"></i> Ubah</a></li>
                                      <li>
                                          @php
                                              $status = $wallet->status == 1 ? 2 : 1;
                                          @endphp
                                          <form action="{{ route('wallets.update.status', [$wallet->wallet_status_id, $status]) }}" method="POST">
                                            @csrf
                                            @method('PATCH')

                                            @if ($wallet->status == 1)
                                                <button type="submit" class="btn btn-primary">Tidak Aktif</button>
                                            @elseif($wallet->status == 2)
                                                <button type="submit" class="btn btn-primary">Aktif</button>
                                            @endif
                                          </form>
                                      </li>
                                    </ul>
                                  </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-wallet').DataTable();
        });
    </script>
@endpush

resources/views/wallets/all_wallet.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'Tambah Dompet')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">DOMPET - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('wallets.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('wallets.all') }}" class="btn btn-secondary">Semua ({{ $count_all }})</a>
                    <a href="{{ route('wallets.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('wallets.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-wallet">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>NAMA</th>
                        <th>REFERENSI</th>
                        <th>DESKRIPSI</th>
                        <th>STATUS</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($wallets as $wallet)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $wallet->name }}</td>
                            <td>{{ $wallet->reference }}</td>
                            <td>{{ $wallet->description }}</td>
                            <td>{{ $wallet->status == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <li class="mb-2">{{ $wallet->name }}</li>
                                      <li><a href="{{ route('wallets.show', $wallet->id) }}"><i class="fas fa-search" style="color: #3056c8;"></i> Detail</a></li>
                                      <li><a href="{{ route('wallets.edit', $wallet->id) }}"><i class="fas fa-edit" style="color: #3056c8;"></i> Ubah</a></li>
                                      <li>
                                          @php
                                              $status = $wallet->status == 1 ? 2 : 1;
                                          @endphp
                                          <form action="{{ route('wallets.update.status', [$wallet->wallet_status_id, $status]) }}" method="POST">
                                            @csrf
                                            @method('PATCH')

                                            @if ($wallet->status == 1)
                                                <button type="submit" class="btn btn-primary">Tidak Aktif</button>
                                            @elseif($wallet->status == 2)
                                                <button type="submit" class="btn btn-primary">Aktif</button>
                                            @endif
                                          </form>
                                      </li>
                                    </ul>
                                  </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-wallet').DataTable();
        });
    </script>
@endpush

resources/views/wallets/create.blade.php
@extends('layouts.master')

@section('title', 'Tambah Dompet')

@section('content')
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-9">
                    <h1 class="h3 mb-2 text-gray-800">DOMPET - Buat Baru</h1>
                </div>
                <div class="col-md-3">
                    <a href="{{ route('wallets.index') }}" class="btn btn-primary">Kelola Dompet</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('wallets.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="name">Nama <span>*</span></label>
                            <input id="name" class="form-control @error('name') is-invalid @enderror" type="text" name="name"
                                value="{{ old('name') }}">

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="reference">Referensi</label>
                                <input id="reference" class="form-control" type="number"
                                    name="reference" value="{{ old('reference') }}">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    <textarea id="description" class="form-control"
                        name="description" maxlength="100">{{ old('description') }}</textarea>
                </div>

                <div class="form-group">
                    <label for="wallet_status_id">Category Status ID</label>
                    <select id="wallet_status_id" class="form-control col-md-6 @error('wallet_status_id') is-invalid @enderror" name="wallet_status_id">
                        <option value="">-- Pilih Status --</option>
                        @foreach ($wallet_statuses as $wallet_status)
                            <option value="{{ $wallet_status->id }}"
                                {{ old('wallet_status_id') == $wallet_status->id ? 'selected' : '' }}>
                                {{ $wallet_status->name }}
                            </option>
                        @endforeach
                    </select>

                    @error('wallet_status_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" class="form-control col-md-6" name="status">
                        <option value="">-- Pilih Status --</option>
                        <option value="1" selected>Aktif</option>
                        <option value="2">Tidak Aktif</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-user">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/wallets/edit.blade.php
@extends('layouts.master')

@section('title', 'Tambah Dompet')

@section('content')
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-9">
                    <h1 class="h3 mb-2 text-gray-800">DOMPET - Ubah</h1>
                </div>
                <div class="col-md-3">
                    <a href="{{ route('wallets.index') }}" class="btn btn-primary">Kelola Dompet</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('wallets.update', $wallet->id) }}" method="POST">
                @csrf
                @method('PATCH')

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="name">Nama <span>*</span></label>
                            <input id="name" class="form-control @error('name') is-invalid @enderror" type="text" name="name"
                                value="{{ old('name', $wallet->name) }}">

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="reference">Referensi</label>
                                <input id="reference" class="form-control" type="number"
                                    name="reference" value="{{ old('reference', $wallet->reference) }}">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    <textarea id="description" class="form-control"
                        name="description" maxlength="100">{{ old('description', $wallet->description) }}</textarea>
                </div>

                <div class="form-group">
                    <label for="wallet_status_id">Category Status ID</label>
                    <select id="wallet_status_id" class="form-control col-md-6 @error('wallet_status_id') is-invalid @enderror" name="wallet_status_id">
                        <option value="">-- Pilih Status --</option>
                        @foreach ($wallet_statuses as $wallet_status)
                            <option value="{{ $wallet_status->id }}"
                                {{ old('wallet_status_id') == $wallet_status->id ? 'selected' : '' }}
                                {{ $wallet->wallet_status_id == $wallet_status->id ? 'selected' : '' }}>
                                {{ $wallet_status->name }}
                            </option>
                        @endforeach
                    </select>

                    @error('wallet_status_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" class="form-control col-md-6" name="status">
                        <option value="">-- Pilih Status --</option>
                        <option value="1" {{ $wallet->status == 1 ? 'selected' : '' }}>Aktif</option>
                        <option value="2" {{ $wallet->status == 2 ? 'selected' : '' }}>Tidak Aktif</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-user">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/wallets/index.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'Tambah Dompet')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">DOMPET - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('wallets.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('wallets.all') }}" class="btn btn-secondary">Semua ({{ $count_all }})</a>
                    <a href="{{ route('wallets.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('wallets.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-wallet">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>NAMA</th>
                        <th>REFERENSI</th>
                        <th>DESKRIPSI</th>
                        <th>STATUS</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($wallets as $wallet)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $wallet->name }}</td>
                            <td>{{ $wallet->reference }}</td>
                            <td>{{ $wallet->description }}</td>
                            <td>{{ $wallet->status == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <li class="mb-2">{{ $wallet->name }}</li>
                                      <li><a href="{{ route('wallets.show', $wallet->id) }}"><i class="fas fa-search" style="color: #3056c8;"></i> Detail</a></li>
                                      <li><a href="{{ route('wallets.edit', $wallet->id) }}"><i class="fas fa-edit" style="color: #3056c8;"></i> Ubah</a></li>
                                      <li>
                                          @php
                                              $status = $wallet->status == 1 ? 2 : 1;
                                          @endphp
                                          <form action="{{ route('wallets.update.status', [$wallet->id, $status]) }}" method="POST">
                                            @csrf
                                            @method('PATCH')

                                            @if ($wallet->status == 1)
                                                <button type="submit" class="btn btn-primary">Tidak Aktif</button>
                                            @elseif($wallet->status == 2)
                                                <button type="submit" class="btn btn-primary">Aktif</button>
                                            @endif
                                          </form>
                                      </li>
                                    </ul>
                                  </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-wallet').DataTable();
        });
    </script>
@endpush