routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function(){
    Route::get('wallets/show/all', 'WalletController@all_wallet')->name('wallets.all');
    Route::get('wallets/show/active', 'WalletController@wallet_active')->name('wallets.active');
    Route::get('wallets/show/not-active', 'WalletController@wallet_not_active')->name('wallets.not-active');
    Route::patch('wallets/update/status/{id}/{status}', 'WalletController@update_status')->name('wallets.update.status');
    Route::resource('wallets', 'WalletController');

    Route::get('categories/show/all', 'CategoryController@all_category')->name('categories.all');
    Route::get('categories/show/active', 'CategoryController@category_active')->name('categories.active');
    Route::get('categories/show/not-active', 'CategoryController@category_not_active')->name('categories.not-active');
    Route::patch('categories/update/status/{id}/{status}', 'CategoryController@update_status')->name('categories.update.status');
    Route::resource('categories', 'CategoryController');

    Route::get('transactions/create/wallet-in', 'TransactionController@create_wallet_in')->name('transactions.create.wallet-in');
    Route::get('transactions/show/wallet-in', 'TransactionController@wallet_in')->name('transactions.wallet-in');
    Route::post('transactions/process/wallet-in', 'TransactionController@process_wallet_in')->name('transactions.process.wallet-in');

    Route::get('transactions/create/wallet-out', 'TransactionController@create_wallet_out')->name('transactions.create.wallet-out');
    Route::get('transactions/show/wallet-out', 'TransactionController@wallet_out')->name('transactions.wallet-out');
    Route::post('transactions/process/wallet-out', 'TransactionController@process_wallet_out')->name('transactions.process.wallet-out');

    Route::get('report/transactions/view', 'ReportController@view_report')->name('reports.view');
    Route::get('report/transactions/show', 'ReportController@show_report')->name('reports.show');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\CategoryStatus;
use App\WalletStatus;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $count_all = DB::table('categories')->count();

        $count_active = DB::table('categories')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('categories')
            ->where('status', 2)
            ->count();

        $categories = Category::all();

        return view('categories.index', [
            'categories' => $categories,
            'count_not_active' => $count_not_active,
            'count_active' => $count_active,
            'count_all' => $count_all
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category_statuses = CategoryStatus::orderBy('name', 'asc')->get();
        return view('categories.create', ['category_statuses' => $category_statuses]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:5',
            'description' => 'max:100',
            'category_status_id' => 'required',
            'status' => 'required'
        ]);

        Category::create([
            'name' => $request->name,
            'description' => $request->description,
            'category_status_id' => $request->category_status_id,
            'status' => $request->status
        ]);

        return redirect()->route('categories.index')->with('success', 'Data kategori berhasil disimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);

        return view('categories.show', [
            'category' => $category
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $category_statuses = CategoryStatus::orderBy('name', 'asc')->get();

        return view('categories.edit', [
            'category' => $category,
            'category_statuses' => $category_statuses
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $request->validate([
            'name' => 'required|min:5',
            'description' => 'max:100',
            'category_status_id' => 'required',
            'status' => 'required'
        ]);

        $category->update([
            'name' => $request->name,
            'description' => $request->description,
            'category_status_id' => $request->category_status_id
        ]);

        return redirect()->route('categories.index')->with('success', 'Data kategori berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function update_status(Request $request, $id, $status)
    {
        $category_status = Category::find($id);
        $category_status->update([
            'status' => $status
        ]);

        return redirect()->route('categories.index')->with('success', 'Status dompet berhasil diubah!');
    }

    public function category_active()
    {
        $categories = DB::table('categories')
            ->where('status', 1)
            ->get();

        $count_all = DB::table('categories')->count();

        $count_active = DB::table('categories')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('categories')
            ->where('status', 2)
            ->count();

        return view('categories.active', [
            'categories' => $categories,
            'count_active' => $count_active,
            'count_not_active' => $count_not_active,
            'count_all' => $count_all
        ]);
    }

    public function category_not_active()
    {
        $categories = DB::table('categories')
            ->where('status', 2)
            ->get();

        $count_all = DB::table('categories')->count();

        $count_active = DB::table('categories')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('categories')
            ->where('status', 2)
            ->count();

        return view('categories.not_active', [
            'categories' => $categories,
            'count_active' => $count_active,
            'count_not_active' => $count_not_active,
            'count_all' => $count_all
        ]);
    }

    public function all_category()
    {
        $categories = DB::table('categories')
                ->get();

        $count_all = DB::table('categories')->count();

        $count_active = DB::table('categories')
            ->where('status', 1)
            ->count();

        $count_not_active = DB::table('categories')
            ->where('status', 2)
            ->count();

        return view('categories.not_active', [
            'categories' => $categories,
            'count_active' => $count_active,
            'count_not_active' => $count_not_active,
            'count_all' => $count_all
        ]);
    }
}

resources/views/categories/active.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'List Kategori')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">KATEGORI - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('categories.all') }}" class="btn btn-secondary">Semua ({{ $count_all }})</a>
                    <a href="{{ route('categories.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('categories.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-categories">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>NAMA</th>
                        <th>DESKRIPSI</th>
                        <th>STATUS</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->description }}</td>
                            <td>{{ $category->status == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <li class="mb-2">{{ $category->name }}</li>
                                      <li><a href="{{ route('categories.show', $category->id) }}"><i class="fas fa-search" style="color: #3056c8;"></i> Detail</a></li>
                                      <li><a href="{{ route('categories.edit', $category->id) }}"><i class="fas fa-edit" style="color: #3056c8;"></i> Ubah</a></li>
                                      <li>
                                          @php
                                              $status = $category->status == 1 ? 2 : 1;
                                          @endphp
                                          <form action="{{ route('categories.update.status', [$category->category_status_id, $status]) }}" method="POST">
                                            @csrf
                                            @method('PATCH')

                                            @if ($category->status == 1)
                                                <button type="submit" class="btn btn-primary">Tidak Aktif</button>
                                            @elseif($category->status == 2)
                                                <button type="submit" class="btn btn-primary">Aktif</button>
                                            @endif
                                          </form>
                                      </li>
                                    </ul>
                                  </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-categories').DataTable();
        });
    </script>
@endpush

resources/views/categories/create.blade.php
@extends('layouts.master')

@section('title', 'Tambah Kategori')

@section('content')
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-9">
                    <h1 class="h3 mb-2 text-gray-800">KATEGORI - Buat Baru</h1>
                </div>
                <div class="col-md-3">
                    <a href="{{ route('categories.index') }}" class="btn btn-primary">Kelola Kategori</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('categories.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Nama <span>*</span></label>
                    <input id="name" class="form-control col-md-6 @error('name') is-invalid @enderror" type="text" name="name"
                        value="{{ old('name') }}">

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    <textarea id="description" class="form-control"
                        name="description" maxlength="100">{{ old('description') }}</textarea>
                </div>

                <div class="form-group">
                    <label for="category_status_id">Category Status ID</label>
                    <select id="category_status_id" class="form-control col-md-6 @error('category_status_id') is-invalid @enderror" name="category_status_id">
                        <option value="">-- Pilih Status --</option>
                        @foreach ($category_statuses as $category_status)
                            <option value="{{ $category_status->id }}"
                                {{ old('category_status_id') == $category_status->id ? 'selected' : '' }}>
                                {{ $category_status->name }}
                            </option>
                        @endforeach
                    </select>

                    @error('category_status_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" class="form-control col-md-6" name="status">
                        <option value="">-- Pilih Status --</option>
                        <option value="1" selected>Aktif</option>
                        <option value="2">Tidak Aktif</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-user">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.master')

@section('title', 'Ubah Kategori')

@section('content')
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-9">
                    <h1 class="h3 mb-2 text-gray-800">KATEGORI - Ubah</h1>
                </div>
                <div class="col-md-3">
                    <a href="{{ route('categories.index') }}" class="btn btn-primary">Kelola Kategori</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('categories.update', $category->id) }}" method="POST">
                @csrf
                @method('PATCH')

                <div class="form-group">
                    <label for="name">Nama <span>*</span></label>
                    <input id="name" class="form-control col-md-6 @error('name') is-invalid @enderror" type="text" name="name"
                        value="{{ old('name', $category->name) }}">

                    @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    <textarea id="description" class="form-control"
                        name="description" maxlength="100">{{ old('description', $category->description) }}</textarea>
                </div>

                <div class="form-group">
                    <label for="category_status_id">Category Status ID</label>
                    <select id="category_status_id" class="form-control col-md-6 @error('category_status_id') is-invalid @enderror" name="category_status_id">
                        <option value="">-- Pilih Status --</option>
                        @foreach ($category_statuses as $category_status)
                            <option value="{{ $category_status->id }}"
                                {{ old('category_status_id') == $category_status->id ? 'selected' : '' }}
                                {{ $category->category_status_id == $category_status->id ? 'selected' : '' }}>
                                {{ $category_status->name }}
                            </option>
                        @endforeach
                    </select>

                    @error('category_status_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="status">Status</label>
                    <select id="status" class="form-control col-md-6" name="status">
                        <option value="">-- Pilih Status --</option>
                        <option value="1" {{ $category->status == 1 ? 'selected' : '' }}>Aktif</option>
                        <option value="2" {{ $category->status == 2 ? 'selectd' : '' }}>Tidak Aktif</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-user">
                    Submit
                </button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'List Kategori')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">KATEGORI - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('categories.all') }}" class="btn btn-secondary">Semua ({{ $count_all }})</a>
                    <a href="{{ route('categories.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('categories.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-categories">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>NAMA</th>
                        <th>DESKRIPSI</th>
                        <th>STATUS</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->description }}</td>
                            <td>{{ $category->status == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <li class="mb-2">{{ $category->name }}</li>
                                      <li><a href="{{ route('categories.show', $category->id) }}"><i class="fas fa-search" style="color: #3056c8;"></i> Detail</a></li>
                                      <li><a href="{{ route('categories.edit', $category->id) }}"><i class="fas fa-edit" style="color: #3056c8;"></i> Ubah</a></li>
                                      <li>
                                          @php
                                              $status = $category->status == 1 ? 2 : 1;
                                          @endphp
                                          <form action="{{ route('categories.update.status', [$category->category_status_id, $status]) }}" method="POST">
                                            @csrf
                                            @method('PATCH')

                                            @if ($category->status == 1)
                                                <button type="submit" class="btn btn-primary">Tidak Aktif</button>
                                            @elseif($category->status == 2)
                                                <button type="submit" class="btn btn-primary">Aktif</button>
                                            @endif
                                          </form>
                                      </li>
                                    </ul>
                                  </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-categories').DataTable();
        });
    </script>
@endpush

resources/views/categories/not_active.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'List Kategori')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">KATEGORI - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('categories.all') }}" class="btn btn-secondary">Semua ({{ $count_all }})</a>
                    <a href="{{ route('categories.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('categories.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-categories">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>NAMA</th>
                        <th>DESKRIPSI</th>
                        <th>STATUS</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->description }}</td>
                            <td>{{ $category->status == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    <span class="caret"></span></button>
                                    <ul class="dropdown-menu">
                                      <li class="mb-2">{{ $category->name }}</li>
                                      <li><a href="{{ route('categories.show', $category->id) }}"><i class="fas fa-search" style="color: #3056c8;"></i> Detail</a></li>
                                      <li><a href="{{ route('categories.edit', $category->id) }}"><i class="fas fa-edit" style="color: #3056c8;"></i> Ubah</a></li>
                                      <li>
                                          @php
                                              $status = $category->status == 1 ? 2 : 1;
                                          @endphp
                                          <form action="{{ route('categories.update.status', [$category->category_status_id, $status]) }}" method="POST">
                                            @csrf
                                            @method('PATCH')

                                            @if ($category->status == 1)
                                                <button type="submit" class="btn btn-primary">Tidak Aktif</button>
                                            @elseif($category->status == 2)
                                                <button type="submit" class="btn btn-primary">Aktif</button>
                                            @endif
                                          </form>
                                      </li>
                                    </ul>
                                  </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-categories').DataTable();
        });
    </script>
@endpush

resources/views/categories/show.blade.php
@extends('layouts.master')

@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/css/jquery.dataTables.min.css">
    <style>
        #table-wallet tr th {
            background-color: #3056c8;
            color: #fff !important;
        }

        .dropdown-menu {
            padding: 1em;
        }
    </style>
@endpush

@section('title', 'List Kategori')

@section('content')
<div class="container">
    @include('layouts.include.alert')
    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="h3 mb-2 text-gray-800">DOMPET - Aktif</h1>
                </div>
                <div class="col-md-5">
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">Buat Baru</a>
                    <a href="{{ route('categories.active') }}" class="btn btn-success">Aktif ({{ $count_active }})</a>
                    <a href="{{ route('categories.not-active') }}" class="btn btn-danger">Tidak Aktif ({{ $count_not_active }})</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table-categories">
                <thead>
                    <tr>
                        <th>NAMA</th>
                        <th>DESKRIPSI</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $category[0]->name }}</td>
                        <td>{{ $category[0]->description }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/jquery.dataTables.min.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.20/js/dataTables.bootstrap.min.js"></script> --}}
    <script>
        $(document).ready( function () {
            $('#table-categories').DataTable();
        });
    </script>
@endpush