routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function(){
    Route::get('wallets/show/all', 'WalletController@all_wallet')->name('wallets.all');
    Route::get('wallets/show/active', 'WalletController@wallet_active')->name('wallets.active');
    Route::get('wallets/show/not-active', 'WalletController@wallet_not_active')->name('wallets.not-active');
    Route::patch('wallets/update/status/{id}/{status}', 'WalletController@update_status')->name('wallets.update.status');
    Route::resource('wallets', 'WalletController');

    Route::get('categories/show/all', 'CategoryController@all_category')->name('categories.all');
    Route::get('categories/show/active', 'CategoryController@category_active')->name('categories.active');
    Route::get('categories/show/not-active', 'CategoryController@category_not_active')->name('categories.not-active');
    Route::patch('categories/update/status/{id}/{status}', 'CategoryController@update_status')->name('categories.update.status');
    Route::resource('categories', 'CategoryController');

    Route::get('transactions/create/wallet-in', 'TransactionController@create_wallet_in')->name('transactions.create.wallet-in');
    Route::get('transactions/show/wallet-in', 'TransactionController@wallet_in')->name('transactions.wallet-in');
    Route::post('transactions/process/wallet-in', 'TransactionController@process_wallet_in')->name('transactions.process.wallet-in');

    Route::get('transactions/create/wallet-out', 'TransactionController@create_wallet_out')->name('transactions.create.wallet-out');
    Route::get('transactions/show/wallet-out', 'TransactionController@wallet_out')->name('transactions.wallet-out');
    Route::post('transactions/process/wallet-out', 'TransactionController@process_wallet_out')->name('transactions.process.wallet-out');

    Route::get('report/transactions/view', 'ReportController@view_report')->name('reports.view');
    Route::get('report/transactions/show', 'ReportController@show_report')->name('reports.show');
});

resources/views/layouts/include/main-page/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Maju Bersama Atomic Indonesia &copy; 2020</span>
        </div>
    </div>
</footer>

resources/views/layouts/include/main-page/head.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>@yield('title')</title>

  <!-- Custom fonts for this template-->
  <link href="{{ asset('assets/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ asset('assets/css/sb-admin-2.min.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/fontawesome.min.css">
  <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker.min.css') }}">

  @stack('style')

</head>

<body id="page-top">

resources/views/layouts/include/main-page/menu.blade.php
 <!-- Heading -->
 <div class="sidebar-heading">
     Menu
 </div>

 <!-- Nav Item - Pages Collapse Menu -->
 <li class="nav-item">
     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
         aria-controls="collapseTwo">
         <i class="fas fa-fw fa-cog"></i>
         <span>Master</span>
     </a>
     <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
         <div class="bg-white py-2 collapse-inner rounded">
             <a class="collapse-item" href="{{ route('wallets.index') }}">Dompet</a>
             <a class="collapse-item" href="{{ route('categories.index') }}">Kategori</a>
         </div>
     </div>
 </li>

 <!-- Nav Item - Utilities Collapse Menu -->
 <li class="nav-item">
     <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
         aria-controls="collapseUtilities">
         <i class="fas fa-fw fa-wrench"></i>
         <span>Transaksi</span>
     </a>
     <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
         <div class="bg-white py-2 collapse-inner rounded">
             <a class="collapse-item" href="{{ route('transactions.wallet-in') }}">Dompet Masuk</a>
             <a class="collapse-item" href="{{ route('transactions.wallet-out') }}">Dompet Keluar</a>
         </div>
     </div>
 </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReport" aria-expanded="true"
        aria-controls="collapseReport">
        <i class="fas fa-download"></i>
        <span>Laporan</span>
    </a>
    <div id="collapseReport" class="collapse" aria-labelledby="headingReport" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{{ route('reports.view') }}">Transaksi</a>
        </div>
    </div>
</li>

resources/views/layouts/include/main-page/script.blade.php
 <!-- Bootstrap core JavaScript-->
 <script src="{{ asset('assets/vendor/jquery/jquery.min.js') }}"></script>
 <script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

 <!-- Core plugin JavaScript-->
 <script src="{{ asset('assets/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

 <!-- Custom scripts for all pages-->
 <script src="{{ asset('assets/js/sb-admin-2.min.js') }}"></script>

 @stack('script')

</body>

</html>

resources/views/layouts/include/main-page/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">Dompet {{ Auth::user()->name }}</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="{{ route('home') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

   @include('layouts.include.main-page.menu')

  </ul>

resources/views/layouts/include/main-page/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <div class="topbar-divider d-none d-sm-block"></div>

      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
          <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal" onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </div>
      </li>

    </ul>

  </nav>